[build]
  command = "npm run build"
  publish = ".next" 
  functions = "netlify/functions"
  
  
[build.environment]
  NODE_VERSION = "20" 
  PG_STRING = "https://abduljabbar-portfolio.deno.dev"

[[plugins]]
  package = "@netlify/plugin-nextjs"