[build]
  command = "npm run build"
  publish = ".next" 
  functions = "netlify/functions"

  
[build.environment]
  NODE_VERSION = "20" 
  NEXT_PUBLIC_BACKEND_URL="https://pyoaowwarxwvraghsvpz.supabase.co/functions/v1"
  BACKEND_URL="https://pyoaowwarxwvraghsvpz.supabase.co/functions/v1"
  NEXT_DISABLE_NETLIFY_EDGE = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"