[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20" 
  PG_STRING_PROD = "https://abduljabbar-portfolio.deno.dev/gql"

[[plugins]]
  package = "@netlify/plugin-nextjs"
